name: Perform tests and build apk

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: 17

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: lint check
        run: ./gradlew lintDebug

      - name: Upload lint check report
        uses: actions/upload-artifact@v3
        with:
          name: lint-results-debug
          path: app/build/reports/lint-results-debug.html

      - name: Perform unit tests
        run: ./gradlew test

      - name: Upload unit test report
        uses: actions/upload-artifact@v3
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
